### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by polluks** [pauloscustodio/perl-CPU-Z80-Assembler#5]
I'm not a Perl expert...
[z80.log](https://github.com/pauloscustodio/perl-CPU-Z80-Assembler/files/12420843/z80.log)

**Comment by pauloscustodio** [comment]
What command did you run?

The way to build a Perl module from source is:
```
perl Makefile.PL
make
make test
make install
```

Alternatively you can install directly from CPAN:
```
cpan CPU::Z80::Assembler
```

**Comment by pauloscustodio** [comment]
Closing this.
